# Letakkan di baris paling atas
allow_anonymous true
persistence false

# Listener MQTT untuk ESP32 (lewat TCP Proxy Railway)
listener 1883 0.0.0.0
protocol mqtt

# Listener Websockets untuk Website (lewat Domain HTTPS Railway)
listener 8080 0.0.0.0
protocol websockets